"""add language to posts

Revision ID: 379af21ac09a
Revises: e5f99aced9e3
Create Date: 2018-10-30 10:38:28.933422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379af21ac09a'
down_revision = 'e5f99aced9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
